### ISSUE TITLE
MVCアーキテクチャについて

### ISSUE THREAD

**Issue by MASAYUKI-ABE** [AbeMori/Tetris#1]

**Comment by takuaki** [comment]
Wikiに大体の役割を洗い出しておいてください

**Comment by MASAYUKI-ABE** [comment]
了解でございます。
mainはおいおい

**Comment by MASAYUKI-ABE** [comment]
done。こんなもんかな？
https://github.com/AbeMori/Tetris/wiki/%E9%96%8B%E7%99%BA%E9%80%B2%E3%82%81%E6%96%B9

**Comment by takuaki** [comment]
これからPRしましょう。公開レポジトリforkしてください。
昨日pushした分については確認してください。宜しくお願いします。

公開レポジトリにもpushできますが、しないように。（merge用の権限がgithubになさそう..）
