### ISSUE TITLE
requirements.txtがほしい

### ISSUE THREAD

**Issue by motomizuki** [AbeMori/Tetris#4]
プロジェクトで使用している依存ライブラリをリポジトリに含めてください。
pipを使用しているなら

```
pip freeze >  requirements.txt
```

で依存ライブラリを出力できます。

```
pip install -r  requirements.txt
```
で依存ライブラリのインストールができます。

**Comment by motomizuki** [comment]
その他実行までの、インストール手順、起動方法的なものがほしい。

**Comment by MASAYUKI-ABE** [comment]
たしかに。
そういえばこれPython3のスタンドアロンなアプリなんだけど、ふつうにPython3いれないとつかえなんだよね？

**Comment by takuaki** [comment]
指摘ありがとう！
追加しました。

**Comment by MASAYUKI-ABE** [comment]
多すぎない？？Flaskとか使ってないはずだけど

**Comment by motomizuki** [comment]
プロジェクトに必要なものだけを追記してください。
 scikit-learnとか入れるのだるいですｗ

virtualenvやpyenvで開発時の環境を切り分けるとよいでしょう

+ https://virtualenv.pypa.io/en/latest/
+ https://github.com/yyuu/pyenv

**Comment by takuaki** [comment]
阿部しありがとう
